# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.TextField(db_index=True),
        ),
    ]
